name: resizable_text
description: A new Flutter package project.
version: 0.0.2
publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7 <4.0.0"

dependencies:
  breakpoints_utilities:
    path: packages/breakpoints_utilities/
  flutter:
    sdk: flutter
  meta: ^1.10.0
  screen_size_provider:
    path: packages/screen_size_provider/

dev_dependencies:
  melos: ^4.0.0
