name: resizable_text
description: A new Flutter package project.
version: 0.0.2
publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.19.5 <4.0.0"

dependencies:
  breakpoints_utilities:
    path: packages/breakpoints_utilities/
  flutter:
    sdk: flutter
  meta: ^1.11.0
  screen_size_provider:
    path: packages/screen_size_provider/

dev_dependencies:
  melos: ^5.2.2
